"""Create admin and Russian Loto tables

Revision ID: 44bedfa7aeac
Revises: 
Create Date: 2023-06-17 13:50:52.336964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44bedfa7aeac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=50), nullable=False),
    sa.Column('password', sa.VARCHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Player',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=45), nullable=False),
    sa.Column('times_won', sa.Integer(), nullable=False),
    sa.Column('times_led', sa.Integer(), nullable=False),
    sa.Column('times_played', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Session',
    sa.Column('chat_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=45), nullable=False),
    sa.Column('status', sa.VARCHAR(length=45), nullable=False),
    sa.Column('start_date', sa.DATETIME(), nullable=False),
    sa.Column('last_event_date', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_table('Barrel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bag_id', sa.Integer(), nullable=False),
    sa.Column('barrel_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bag_id'], ['Session.chat_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('SessionPlayer',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.VARCHAR(length=45), nullable=False),
    sa.Column('card_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['Player.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['Session.chat_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', 'player_id')
    )
    op.create_table('CardCell',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('cell_index', sa.Integer(), nullable=False),
    sa.Column('barrel_number', sa.Integer(), nullable=True),
    sa.Column('is_covered', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['SessionPlayer.player_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['SessionPlayer.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('CardCell')
    op.drop_table('SessionPlayer')
    op.drop_table('Barrel')
    op.drop_table('Session')
    op.drop_table('Player')
    op.drop_table('Admin')
    # ### end Alembic commands ###
